startup_description:
  description: >
    На основе предоставленных маркетинговых исследований и чернового описания идеи создать убедительное 
    описание стартапа, принимая во внимание требования предъявляемые государством и инвесторами.
    Основные требования к стартапам:
    ###
    Возраст и регистрация:
    - Компания должна быть не старше 5 лет с момента создания
    - Для биотехнологических и энергетических компаний - до 7 лет
    - Головной офис или представительство должны находиться в стране регистрации

    Финансовые критерии:
    - Компания не должна быть публичной
    - Запрещено распределение дивидендов

    Требования к персоналу:
    - Минимум 60% сотрудников должны иметь трудовой договор в стране регистрации
    - Для кооперативов учитываются работающие члены и партнеры

    Инновационность:
    - Компания должна развивать инновационный проект
    - Бизнес-модель должна быть масштабируемой
    - Проект должен включать технологические риски

    Ограничения
    - Компания не может получить статус стартапа, если
    - Имеет задолженности по налогам
    - Была осуждена за экономические преступления
    - Лишена права на получение государственных субсидий
    
    Критерии оценки
    Инновационность оценивается по:
    - Наличию финансирования НИОКР
    - Наличию патентов и собственных разработок
    - Использованию новых технологий
    - Внедрению инновационных процессов
    
    Рыночный потенциал:
    - Анализ спроса и предложения в секторе
    - Стратегия привлечения клиентов
    - Конкурентные преимущества
    - Масштабируемость бизнес-модели
    ###

    Необходимо:
    1. Проанализировать все предоставленные маркетинговые отчеты
    2. Выделить ключевые рыночные возможности и потребности
    3. Определить наиболее перспективные направления развития
    4. Сформулировать уникальное ценностное предложение
    5. Подчеркнуть инновационность и масштабируемость проекта
    6. Включить конкретные метрики и показатели из исследований
    7. Продемонстрировать потенциал роста и привлекательность для инвесторов
    8. Учесть специфику требований предъявляемые государством и инвесторами и критерии для получения стартап-визы

    Стартап должен смотреться адекватным и жизнеспособным (помни что это стартап, а не корпорация), имея примерные показатели:
    - Начальная команда не более 5 человек
    - Трудоустроить до 20 человек
    - инвестиции не более 200 тыс. евро
    - Учитывай сроки реализации проекта адекватно масштабам проекта. Исходи из того, что сегодня начало 2025 года.
    
    Важно!
     Сейчас не нужно указывать "Финансовые показатели и прогнозы" стартапа (объемы выручки, прибыли),
     все финансовые показатели и прогнозы будут разработаны в отдельном документе.
     Это не является предметом маркетинговых исследований и не может быть получен из них.

    # Черновое описание идеи:
    {structured_idea}

    # Ниже приведены результаты маркетинговых исследований, которые помогут в создании описания стартапа:
    ## **Анализ рыночной ниши и потенциала роста**
    """
    {demand_analysis}
    """

    ## **Конкурентные преимущества**
    """
    {competitive_level}
    """

    ## **Текущие достижения и планы развития**
    """
    {scalability}
    """

    ## **Барьеры входа**
    """
    {barriers_to_entry}
    """

  expected_output: >
    Структурированное описание стартапа, включающее:
    - Краткое резюме проекта (executive summary)
    - Описание проблемы и решения с опорой на данные исследований
    - Анализ рыночной ниши и потенциала роста
    - Детальное описание технологической составляющей
    - Конкурентные преимущества и барьеры входа
    - Текущие достижения и планы развития
    - Финансовые показатели и прогнозы
    - Команда и экспертиза
    
    Формат: Markdown документ с четкой структурой и подзаголовками.
    Стиль: Профессиональный, с акцентом на факты и метрики.
    
  agent: founder
  async_execution: false