patent_research:
  description: >
    Провести анализ потенциально патентуемых технологий в проекте:
    - Алгоритмы машинного обучения для обработки данных IoT
    - Методы оптимизации энергопотребления в сенсорных сетях
    - Архитектурные решения для распределенных IoT систем
    Определить их уникальность и патентную чистоту.
    Описание бизнес-модели проекта приведен ниже:
    {business_model}
  expected_output: >
    Структурированный отчет с описанием 3-5 ключевых технологий,
    их инновационности и потенциала для патентования.
    Включить предварительную оценку патентоспособности.
  agent: legal_advisor

patent_strategy:
  description: >
    На основе результатов патентного исследования разработать:
    - График подачи патентных заявок на 2025-2026 годы
    - Оценку затрат на патентование
    - Стратегию защиты IP в ключевых регионах (EU, US)
    - План действий по подготовке патентной документации
  expected_output: >
    Детальный план патентования с временными и финансовыми показателями,
    включая предварительные формулы изобретений.
  agent: legal_advisor

executive_summary:
  description: >
    Подготовить убедительное описание патентной стратегии для бизнес-плана:
    - Подчеркнуть инновационность технологических решений
    - Описать текущий статус разработок и планы по патентованию
    - Включить конкретные сроки и цифры
    - Показать влияние патентов на конкурентоспособность
    Стиль должен быть уверенным, но реалистичным.
  expected_output: >
    Профессиональное описание патентной стратегии объемом 2-3 параграфа,
    демонстрирующее серьезный подход к защите IP и потенциал проекта.
    Текст должен быть понятен как техническим специалистам, так и инвесторам.
    Текст должен быть отформатирован и структурирован.
  agent: founder
  async_execution: false